---
title: "Live session 1.1: Multiple linear regression"
author: "Matthew Ragoza"
date: "1/14/2022"
always_allow_html: true
output:
  html_document:
    df_print: paged
    toc: false
    number_sections: false
    toc_depth: '3'
    code_folding: show
---

## Read in the data.

```{r}
setwd('C:\\Users\\mtr22\\Code\\BIOST2049\\module-1\\live-session-1')
data <- read.csv('Module1Topics1and2Example.csv')
data
```

## Fit the linear regression model.

```{r}
model <- lm(y ~ x1 + x2, data=data)
summary(model)
```

## Display the ANOVA table.

```{r}
anova(model)
```

## Compute predicted values.

```{r}
data$yhat <- predict(model)
data$yhat
```

## Compare three linear regression models.

```{r}
model1 <- lm(y ~ x1, data=data)
model2 <- lm(y ~ x2, data=data)
model3 <- lm(y ~ x1 + x2, data=data)
c(
    summary(model1)$r.squared,
    summary(model2)$r.squared,
    summary(model3)$r.squared
)
```
## Fit a model on centered data.

```{r}
data$x1_c <- scale(data$x1, center=TRUE, scale=FALSE)
data$x2_c <- scale(data$x2, center=TRUE, scale=FALSE)
model_c <- lm(y ~ x1_c + x2_c, data=data)
summary(model_c)
```

## Compare predicted values.

```{r}
data$yhat_c <- predict(model_c)
data[c('yhat', 'yhat_c')]
```

## Predict values for new data.

```{r}
newdata <- data.frame(x1=2.8, x2=7)
newdata$yhat <- predict(model, newdata)
newdata
```